[workspace]
members = [
    "hmac-auth",
    "hmac-auth/sign",
    "jaq",
    "weather",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
component-init = { git = "https://github.com/dicej/component-init" }
hex = "0.4"
hmac = "0.12.1"
serde_json = "1.0.140"
sha2 = "0.10.9"
wstd = "0.5.3"
