[package]
name = "jaq-http"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
component-init.workspace = true
hifijson = "*"
jaq-core = "2.2.0"
jaq-json = { version = "1.1.2", features = ["serde_json"] }
jaq-std = "2.1.1"
serde_json = "1.0.140"
wstd.workspace = true
