[package]
name = "hmac-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
component-init.workspace = true
hex.workspace = true
hmac.workspace = true
serde_json.workspace = true
sha2.workspace = true
wstd.workspace = true
