name: CI

on:
  pull_request:
  push:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_lint:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasip2
          components: rustfmt, clippy

      - name: Install wasmtime
        uses: bytecodealliance/actions/wasmtime/setup@v1

      - name: Check
        run: cargo check --all --target wasm32-wasip2

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all
